config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do
    get '/' => 'homes#top'
    patch '/order_details/:id' => 'order_details#update'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
  end

# get '/customers/is_deleted' => 'public/customers#is_deleted'
namespace :public, path: "" do
  get '/customers/my_page' => 'customers#show'
  get '/customers/unsubscribe' => 'customers#unsubscribe'
  patch '/customers/withdraw' => 'customers#withdraw'
  get '/' => 'homes#top'
  get '/about' => 'homes#about'
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :customers, only: [:edit, :update]
  resources :items, only: [:index, :show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true



  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  def add_tax_price
    (self.price * 1.10).round
  end

  def self.search(search)
    if search
      Item.where(['name LIKE?', "#{search}%"])
    else
      Item.all
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path, notice: "You have created item successfully"
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path, notice: "You have updated item successfully"
    else
      redirect_to public_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <h2 class="text-start">Edit Item</h2>
      <%= form_with model: @item, url: admin_item_path do |f| %>
      <div class="row row-cols-2 g-1">
        <div class="text-center w-25"><%= f.label :image, "商品画像", class: "mt-2 me-3" %></div><div class="w-75"><%= f.file_field :image, class: "form-control", accept: 'image/*' %></div>
        <div class="text-center w-25"><%= f.label :name, "商品名", class: "mt-2 me-3" %></div><div class="w-75"><%= f.text_field :name, class: "form-control" %></div>
        <div class="text-center w-25"><%= f.label :introduction, "商品説明", class: "mt-2 me-3" %></div><div class="w-75"><%= f.text_area :introduction, class: "form-control", size: "10x5" %></div>
        <div class="text-center w-25"><%= f.label :genre_id, "ジャンル", class: "mt-2 me-3" %></div><div class="w-75"><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name),{}, class: "form-select" %></div>
        <div class="text-center w-25"><%= f.label :price, "税抜価格", class: "mt-2 me-3" %></div><div class="w-75"><%= f.text_field :price, class: "form-control" %></div>
        <div class="text-center w-25"><p class="mt-2 me-3">販売ステータス</p></div><div class="w-75"><%= f.radio_button :is_active, "true", class: "mt-2" %><%= f.label :is_active, "販売中", class: "mt-2 me-3" %> <%= f.radio_button :is_active, "false", class: "mt-2" %><%= f.label :is_active, "販売停止中", class: "mt-2" %></div>
      </div>
      <div class="col text-center"><%= link_to :back do %><button class="btn btn-danger px-4 me-3">Back</button><% end %><%= f.submit "Update", class: 'btn btn-dark px-4' %><% end %></div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <div class="row row-cols-2"><div><h2 class="text-start">Items Index</h2></div><div class="text-end"><%= link_to new_admin_item_path do %><button class="btn btn-dark rounded-circle p-0" style="width:2rem;height:2rem;"><i class="fas fa-plus"></i></button><% end %></div></div>
      <table class="table">
        <thead class="text-center">
          <tr>
            <th>Item ID</th>
            <th>Item name</th>
            <th>tax excluded price</th>
            <th>Genre</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody class="text-center">
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to admin_item_path(item), class: "link-dark" do %><%= item.name %><% end %></td>
            <td><%= item.price %></td>
            <td><%= item.genre.name %></td>
            <td><% if item.is_active == true %><span class="text-success"><strong>販売中</strong></span><% else %><span class="text-muted">販売停止中</span><% end %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <h2 class="text-start">Add Item</h2>
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
      <div class="row row-cols-2 g-1">
        <div class="text-center w-25"><%= f.label :image, "商品画像", class: "mt-2 me-3" %></div><div class="w-75"><%= f.file_field :image, class: "form-control", accept: 'image/*' %></div>
        <div class="text-center w-25"><%= f.label :name, "商品名", class: "mt-2 me-3" %></div><div class="w-75"><%= f.text_field :name, class: "form-control" %></div>
        <div class="text-center w-25"><%= f.label :introduction, "商品説明", class: "mt-2 me-3" %></div><div class="w-75"><%= f.text_area :introduction, class: "form-control", size: "10x5" %></div>
        <div class="text-center w-25"><%= f.label :genre_id, "ジャンル", class: "mt-2 me-3" %></div><div class="w-75"><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name),{}, class: "form-select" %></div>
        <div class="text-center w-25"><%= f.label :price, "税抜価格", class: "mt-2 me-3" %></div><div class="w-75"><%= f.text_field :price, class: "form-control" %></div>
        <div class="text-center w-25"><p class="mt-2 me-3">販売ステータス</p></div><div class="w-75"><%= f.radio_button :is_active, "true", class: "mt-2" %><%= f.label :is_active, "販売中", class: "mt-2 me-3" %> <%= f.radio_button :is_active, "false", class: "mt-2" %><%= f.label :is_active, "販売停止中", class: "mt-2" %></div>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-8 col-lg-5 mx-auto text-center">
    <%= f.submit "Add Item", class: 'btn btn-dark px-4' %><% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container-fluid">
  <div class="col-sm-12 col-md-8 col-lg-6 mx-auto">
    <h2>Item Detail</h2>

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-2">
      <div><%= image_tag @item.get_image, size: "250x250", class: "mt-3 rounded" %></div>
      <div>
        <table class="table table-borderless mt-2">
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td>税込価格(税抜価格)</td>
            <td><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td><% if @item.is_active == true %><span class="text-success"><strong>販売中</strong></span><% else %><span class="text-muted">販売停止中</span><% end %></td>
          </tr>
        </table>
      </div>
    </div>
    <div class="text-center"><%= link_to edit_admin_item_path(@item.id) do %><button class="btn btn-dark px-4 me-3">Edit Item</button><% end %><%= link_to :back do %><button class="btn btn-danger px-4">Back</button><% end %></div>
    </div>
</div>