config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do
    get '/' => 'homes#top'
    patch '/order_details/:id' => 'order_details#update'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
  end

# get '/customers/is_deleted' => 'public/customers#is_deleted'
namespace :public, path: "" do
  get '/customers/my_page' => 'customers#show'
  get '/customers/unsubscribe' => 'customers#unsubscribe'
  patch '/customers/withdraw' => 'customers#withdraw'
  get '/' => 'homes#top'
  get '/about' => 'homes#about'
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :customers, only: [:edit, :update]
  resources :items, only: [:index, :show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses
  has_many :cart_items
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 validates :first_name, :last_name, :first_name_kana, :last_name_kana,
            :address, :telephone_number, :postal_code,
            presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
  validates :telephone_number, numericality: { only_integer: true }
  validates :first_name_kana, :last_name_kana,
      format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "カタカナで入力して下さい。"}

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(params_customer)
      redirect_to admin_customers_path
    else
      render "edit"
    end
  end

  private

  def params_customer
    params.require(:customer).permit(:last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container-fluid">
  <div class="col-sm-12 col-md-6 col-lg-5 col-xl-3 mx-auto mt-3">
    <h2>Edit Profile</h2>
    <%= form_with model:@customer, url: admin_customer_path, method: :patch do |f| %>
    <div class="mb-3 mt-3">
      <%= f.label :last_name, "名字" %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :first_name, "名前" %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :last_name_kana, "名字(フリガナ)" %>
      <%= f.text_field :last_name_kana, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :first_name_kana, "名前(フリガナ)" %>
      <%= f.text_field :first_name_kana, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, autocomplete: "email", class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :postal_code, "郵便番号(ハイフンなし)" %>
      <%= f.text_field :postal_code, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :address, "住所" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :telephone_number, "電話番号(ハイフンなし)" %>
      <%= f.text_field :telephone_number, class: "form-control" %>
    </div>
    <div class="mb-3">
      <p>ステータス</p>
      <%= f.radio_button :is_deleted, "false", class: "mt-2", checked: true %><%= f.label :is_deleted, "有効", class: "mt-2 me-3" %> <%= f.radio_button :is_deleted, "true", class: "mt-2" %><%= f.label :is_deleted, "退会", class: "mt-2" %>
    </div>
    <div class="mb-3">
      <%= f.submit "Update Profile", class: "btn btn-dark px-3" %> <%= link_to :back do %><button class="btn btn-danger px-4 me-3">Back</button><% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <h2 class="text-start">Customer Index</h2>
      <table class="table">
        <thead class="text-center">
          <tr>
            <th>Customer ID</th>
            <th>Name</th>
            <th>Mail Address</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody class="text-center">
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to admin_customer_path(customer), class: "link-dark" do %><%= customer.last_name %><%= customer.first_name %><% end %></td>
            <td><%= customer.email %></td>
            <td><% if customer.is_deleted == false %><span class="text-success"><strong>有効</strong></span><% else %><span class="text-muted">退会</span><% end %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container-fluid">
  <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6 mx-auto mt-3">
    <h3 class="mt-3"><%= @customer.last_name %><%= @customer.first_name %>さんの登録情報</h3>

    <table class="table">
      <tr>
        <th class="text-center" width="30%">Customer ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th class="text-center">氏名</th>
        <td><%= @customer.last_name %> <%= @customer.first_name %></td>
      </tr>
      <tr>
        <th class="text-center">氏名(フリガナ)</th>
        <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <th class="text-center">郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th class="text-center">住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th class="text-center">電話番号</th>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th class="text-center">メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th class="text-center">Status</th>
        <td><% if @customer.is_deleted == false %><span class="text-success"><strong>有効</strong></span><% else %><span class="text-muted">退会</span><% end %></td>
      </tr>
    </table>
    <div class="text-end"><%= link_to :back do %><button class="btn btn-danger px-4 me-3">Back</button><% end %><%= link_to edit_admin_customer_path(@customer) do %><button class="btn btn-dark px-3">Edit Profile</button></a><% end %></div>
  </div>
</div>