config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do
    get '/' => 'homes#top'
    patch '/order_details/:id' => 'order_details#update'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
  end

# get '/customers/is_deleted' => 'public/customers#is_deleted'
namespace :public, path: "" do
  get '/customers/my_page' => 'customers#show'
  get '/customers/unsubscribe' => 'customers#unsubscribe'
  patch '/customers/withdraw' => 'customers#withdraw'
  get '/' => 'homes#top'
  get '/about' => 'homes#about'
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :customers, only: [:edit, :update]
  resources :items, only: [:index, :show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item">
        <a href="#" class="nav-link px-2 text-muted">Home</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link px-2 text-muted">About</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link px-2 text-muted">Items</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link px-2 text-muted">Sign up</a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link px-2 text-muted">Sign in</a>
      </li>
    </ul>
  <p class="text-center text-muted"><%= link_to new_admin_session_path, class: "text-decoration-none text-muted" do %>©<% end %> 2022 Nagano Coffee, Inc</p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid py-2">
    <%= link_to public_path , class: "navbar-brand mx-5" do %><%= image_tag 'brand.png', size: "30x30" , class: "d-inline-block align-text-top me-2" %>Nagano Coffee<% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <span class="navbar-text ms-5"><% if customer_signed_in? %>Welcome <%= current_customer.last_name %> さん<% elsif admin_signed_in? %>Welcome Owner<% else %>Welcome to Nagano Coffee<% end %></span>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <% if admin_signed_in? %>
            <%= link_to admin_items_path, class: "nav-link" do %><button type="button" class="btn btn-outline-light px-3"><i class="fas fa-coffee me-1"></i>Items</button><% end %>
          <% else %>
            <%= link_to public_path, class: "nav-link" do %><button type="button" class="btn btn-outline-light px-3"><i class="fa-solid fa-house me-1"></i>Home</button><% end %>
          <% end %>
        </li>

        <li class="nav-item">
          <% if customer_signed_in? %>
            <%= link_to "/customers/my_page", class: "nav-link" do %><button type="button" class="btn btn-outline-light px-3"><i class="fa-solid fa-user me-1"></i>My Page</button><% end %>
          <% elsif admin_signed_in? %>
            <%= link_to admin_customers_path, class: "nav-link" do %><button type="button" class="btn btn-outline-light px-3"><i class="fas fa-user me-1"></i>Customers</button><% end %>
          <% else %>
            <%= link_to public_about_path, class: "nav-link" do %><button type ="button" class="btn btn-outline-light px-3"><i class="fas fa-lightbulb me-1"></i>About</button><% end %>
          <% end %>
        </li>

        <li class="nav-item">
          <% if admin_signed_in? %>
            <%= link_to admin_path, class: "nav-link" do %><button type="button" class="btn btn-outline-light px-3"><i class="fas fa-scroll"></i>Orders</button><% end %>
          <% else %>
            <%= link_to public_items_path, class: "nav-link" do %><button type="button" class="btn btn-outline-light px-3"><i class="fas fa-coffee me-1"></i>Items</button><% end %>
          <% end %>
        </li>

        <li class="nav-item">
          <% if customer_signed_in? %>
            <%= link_to public_cart_items_path, class: "nav-link" do %><button type="button" class="btn btn-outline-light px-3"><i class="fas fa-shopping-cart"></i>Cart</button><% end %>
          <% elsif admin_signed_in? %>
            <%= link_to admin_genres_path, class: "nav-link" do %> <button type="button" class="btn btn-outline-light px-3"><i class="fas fa-list-alt"></i>Genres</button><% end %>
          <% else%>
            <%= link_to new_customer_registration_path, class: "nav-link" do %><button type="button" class="btn btn-outline-light px-3"><i class="fas fa-user-plus"></i>Sign up</button><% end %>
          <% end %>
        </li>

        <li class="nav-item">
          <% if customer_signed_in? %>
            <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link" do %>
              <button type="button" class="btn btn-outline-light px-3"><i class="fas fa-sign-out-alt me-1"></i>Sign out</button><% end %>
          <% elsif admin_signed_in? %>
            <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %><button type="button" class="btn btn-outline-light px-3"><i class="fas fa-sign-out-alt me-1"></i>Sign out</button><% end %>
          <% else %>
            <%= link_to new_customer_session_path , class: "nav-link" do %>
              <button type="button" class="btn btn-outline-light px-3"><i class="fas fa-sign-in-alt me-1"></i>Sign in</button><% end %>
          <% end %>
        </li>
      </ul>
      <%= form_with url: public_items_path, method: :get, class: "d-flex ms-5" do |f| %>
      <%= f.search_field :search, class: "form-control me-2", placeholder: "Item Search..." %>
      <%= f.submit "Search", class: "btn btn-outline-success" %><% end %>
    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nagano Coffee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
    <div class="text-center"><p> <%= notice %> </p><p> <%= flash[:info] %> </p><p> <%= alert %> </p></div>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>